services:
  shell:
    build:
      context: .
    volumes:
      - type: bind
        source: ..
        target: /home/dev/work/
    entrypoint: ["/usr/bin/bash", "-i"]
    stdin_open: true
    tty: true
  latexmk:
    build:
      context: .
    volumes:
      - type: bind
        source: ..
        target: /home/dev/work/
    entrypoint: ["latexmk"]
